Climb roll2
Team3176/Code_2024 pull request #65
Opened 2024-03-20 00:47 UTC by AAgraviador3176

merge and integrate climbroll

2024-03-20 01:00 UTC, jheidegger requested changes
I think the following might help clear things up even more

2024-03-20 01:00 UTC, jheidegger commented on src/main/java/team3176/robot/subsystems/superstructure/climb/Climb.java
> +      if (Constants.getMode() == Mode.REAL) {
re add this check
```suggestion
      if (Constants.getMode() == Mode.REAL && Constants.getRobot() != RobotType.ROBOT_DEFENSE) {
```

2024-03-20 02:24 UTC, char3176 commented
Before merging into integration branch let's see this on 2 motors (1 for each climb) simultaneously or at least in sim.

2024-03-21 23:21 UTC, jheidegger commented
Andrew did you need to merge that in? Now we get all the merge conflicts we were trying to avoid

2024-03-21 23:25 UTC, AAgraviador3176 commented
@jheidegger If I'm being honest, I'm not entirely sure quite yet. We had too many branches for climb roll. They had different parts of the code on them. ClimbRoll2 and Z weren't working separately. Worst comes to worst, we revert to an old branch. I know it's not the perfect time to do this, but this was unfortunately, the solution that came to mind.

2024-03-21 23:27 UTC, jheidegger commented
Gotcha gotcha yep we can cross the bridge when we come to it. Focus on getting it to work and I'll help make sure it can actually get merged in!

2024-03-22 19:13 UTC, char3176 commented
Resolved conflicts.  Merging into integration branch.

2024-03-22 19:13 UTC, merged